export type WeaponName =
  | "Peasant's Pitchfork"
  | "Spiderbite Sickle"
  | "Ratbane Club"
  | "Goblin Cleaver"
  | "Sunfire Greatsword"
  | "Infernal Lance"
  | "Ironclad Halberd"
  | "Bloodthirsty Sabre"
  | "Nightshade Dagger"
  | "Blightbloom Bow"
  | "Voidreaver Axe"
  | "Hellfire Flail"
  | "Frostbite Warhammer"
  | "Runeblade"
  | "Venomfang Spear"
  | "Shadowstrike Dagger"
  | "Whisperwind Bow"
  | "Thunderclap Mace"
  | "Soulreaper Scythe"
  | "Doomblade";
